name: Deploy

on: # Only trigger, when the build workflow succeeded
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  
  build: # synonym for 'deploy'

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v2
    - name: Copy repository contents via scp  # from github repository to server
      uses: appleboy/scp-action@master # predefined action pakage on github
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."  # current working directory
        target: "/var/www/requests"

    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: | #yml syntax meaning multipe lines follow
          ls -lha /var/www/requests 
          sudo systemctl reload requests.service






